version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    versioning-strategy: "widen"
    open-pull-requests-limit: 20
    allow:
      - dependency-type: all
    labels: [ "Dependencies" ]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 20
    labels: [ "Dependencies" ]
