name: tweet
on:
  push:
    tags:
      - '*'
  release:
    types: [ published ]

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Tweet
        uses: snow-actions/tweet@v1.3.0
        with:
          status: |
            We are proud to announce that ${{ github.repository }} · ${{ github.event.release.name }}
            ${{ github.event.release.html_url }} is now released 🚀. #php #totp #hotp
        env:
          CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          CONSUMER_API_SECRET_KEY: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
